### ISSUE TITLE
How to handle base image updates?

### ISSUE THREAD

**Issue by onedr0p** [itscontained/docker#10]
Say ubuntu:focal has a new release, `ubuntu:focal-20201029` how should we handle automating updating the application Dockerfiles?

If we use @DirtyCajunRice favorite keyword `:latest`, we don't have to do anything.

**Comment by dirtycajunrice** [comment]
latest == without the special keyword works well. e.g. we can tag all focal-asdfasdf releases with focal as well, allowing updates to the base images more fluidly but not allowing the next release.

https://github.com/itscontained/docker/blob/af887957b4e15a1cf334f9695b92fcae470240f9/images/ubuntu/Dockerfile#L1
would have to become a build arg based on tag pull like everything else and then all of the images would just go from
https://github.com/itscontained/docker/blob/af887957b4e15a1cf334f9695b92fcae470240f9/images/nzbget/Dockerfile#L1
to `itscontained/ubuntu:focal`
