### ISSUE TITLE
Unable to release new images if they don't exist in dockerhub first

### ISSUE THREAD

**Issue by onedr0p** [itscontained/docker#11]
```
Run ./.github/actions/tag-check-action
🔍 Checking itscontained/nzbget for a tag that matches 21.0
jq: error (at <stdin>:0): Cannot iterate over string ("Resource n...)
Error: Process completed with exit code 5.
```

**Comment by dirtycajunrice** [comment]
There is more to it than this unfortunately. If this were all it was we could catch the error and continue, but in addition:
* quay.io bot tokens are done securely. This means you have to explicitly allow each repository that you want it to be able to write to. I have to add the repo manually and then assign the bot token permissions
* ghcr.io currently makes all initial pushes _**private and user local**_ until made public. That means the account that pushed it has to make it public. Not even the owner of the org can see it making it easier to just push a temporary image and then making the package public prior to pushing the initial real image (until they fix it and they said they were working on it somewhere i just dont remember what page i read it on)

**Comment by onedr0p** [comment]
What do we gain by using multiple registries? Isn't dockerhub enough for now? We can migrate over or add other remotes if there's a specific need.

**Comment by dirtycajunrice** [comment]
Dockerhub is a piece of dog poo. They have repeatedly had speed issues, the have added the pull caps, and they have been generally unreliable. quay has its issues with reliability recently too. Basically eggs in one basket has screwed people over multiple times so I wanted to cover our butts and push to all 3.

**Comment by onedr0p** [comment]
Dockerhub works fine for me ever since adding a pull thru cache on my local network. The company is struggling to keep up, I don't hate them for their changes. They are a small team that didn't merge with Mirantis and they are taking on microsoft and redhat. We're not building out major software here that would require 100% uptime for images. Dockerhub provides the best SEO, integration with the docker app and badges.

GHCR is currently meant to be for testing images as mentioned by this GitHub engineer https://news.ycombinator.com/item?id=24347655

GHCR might also cost for hosting in the future, but it's honestly hard to tell what they will do because it's so new.

As for quay, I don't have anything against it anymore seeing as they finally added the ability to push fat manifests. It does suck if adding a new image, it makes you a blocker on pushing where with dockerhub we can just make it work. 

The point I'm trying to get to is, can we at least drop all but dockerhub and revisit it later? Eggs in one basket shouldn't be a concern for a project like this and the time it would take to move over to another registry would be minutes.

**Comment by onedr0p** [comment]
@DirtyCajunRice I decided to build a container image repository over at [k8s-at-home/container-images](https://github.com/k8s-at-home/container-images), sorry I felt like this was going nowhere here.
