### ISSUE TITLE
Investigate missing tag

### ISSUE THREAD

**Issue by dirtycajunrice** [itscontained/docker#5]
@onedr0p can you look into this? https://github.com/itscontained/docker/runs/1161600781?check_suite_focus=true#step:7:20

**Comment by bjw-s** [comment]
Seems to be caused by this:
https://github.com/itscontained/docker/runs/1161596936?check_suite_focus=true#step:3:12

Looks like some quotes would fix that:
```shell
          if [ -n "${{ github.event.inputs.tag }}" ]
          then
            echo "::set-env name=version::${{ github.event.inputs.tag }}"
          else
            echo "::set-env name=version::$(curl -s "https://radarr.lidarr.audio/v1/update/aphrodite/changes?os=linux" | jq -r '.[0].version')"
          fi
```
